### ISSUE TITLE
Anchor is not inserted before a title with apostraphy

### ISSUE THREAD

**Issue by dashaluna** [dashaluna/hm-content-toc#30]
For example `It's good to learn` The link in the TOC is generated, but the anchor link is not inserted before the actual heading on the content.

**Comment by dashaluna** [comment]
Apostrophe in the TOC is `&#039;` and in the content is `&#8217;`

**Comment by roborourke** [comment]
Can you pass the titles through `sanitise_title_with_dashes()` to fix this?

**Comment by dashaluna** [comment]
So what happens is that headers matches array is generated from matching on the raw content `$content = get_the_content();` https://github.com/dashaluna/hm-content-toc/blob/master/includes/class-content-toc.php#L226 So example, a header with apostrophe will be stored in the matches array as `<h2>It's fun</h2>` 

When when it's time to insert an anchor to the content, it's done in the `add_filter( 'the_content', $func = function ( $content ) use ( &$func, $matches )` here https://github.com/dashaluna/hm-content-toc/blob/master/includes/class-content-toc.php#L246

However, the `$content` in the filter has already been run via `the_content` filters, so the content has got original header text as `<h2>It&#8217;s fun</h2>`. So the two don't match and the anchor is not inserted.

I've tried to do this `$content = apply_filters( 'the_content', get_the_content() );` instead of `$content = get_the_content();` https://github.com/dashaluna/hm-content-toc/blob/master/includes/class-content-toc.php#L226 but that displays white screen without any errors.

I need somehow to preserve `the_content` conversion for the original array of headers, so they could be matched correctly later on.

Not sure what to do. Any suggestions, @tcrsavage ? :)

**Comment by dashaluna** [comment]
Or maybe just run the filter on priority `9` before all default filters kick in, as @sanchothefat suggested?

**Comment by tcrsavage** [comment]
@dashaluna yeah just run before other filters are applied in this case. Can review if unforseen issues occur

**Comment by dashaluna** [comment]
@tcrsavage so I've tried with a priority less than 10, but that didn't work and here is why I think it didn't:

We're adding `add_filter( 'the_content', ...)` filter within the shorcode function - to make sure that it only runs on content where there the shortcode is specified. However, all shortcodes are run on priority `11` -> `add_filter( 'the_content', 'do_shortcode', 11 );` in `wordpress/wp-includes/default-filters.php`, so the TOC shortcode runs and adds our filter, but the content there is already passed through default wp `the_content` filters and it modified. So, in reality our filter runs after all those wp default ones. And it can't match the raw `'` accessed via `get_the_content()` when we generating our list of headers and `&#8217;` in already filtered content.

 Is that the case? What do I do? :)

**Comment by tcrsavage** [comment]
@dashaluna ah ok. So it looks to me like the problem lies here:

https://github.com/dashaluna/hm-content-toc/blob/master/includes/class-content-toc.php#L230

The content being processed to obtain matches hasn't been passed through 'the_content' filter and so you have an effective desync of data where the matches don't contain the required injection of things like html entity handling.

I don't see a pretty solution to this at the moment. If you try to update the handling here to this:

`$content = apply_filters( 'the_content', get_the_content() );`

Then you will end up with an infinite recursion which will break the plugin and pretty much the whole site which it runs on due to the fact that passing content through the `the_content` filter will call your shortcode handling, which will call the `the_content` filter etc.

For now, lets try doing this as a quick fix and maybe we can discuss more elegant solutions down the line:

```
remove_shortcode( 'hm_content_toc' ); 
$content = apply_filters( 'the_content', get_the_content() );
add_shortcode( 'hm_content_toc', array( $this, 'shortcode' ) );
```

**Comment by dashaluna** [comment]
@tcrsavage good thinking - make it work now and think of better solution later.

Sadly, that didn't quite work. It escaped the shortcode text into `[hm_content_toc title=&#8221;The TOC&#8221; headers=&#8221;h2, h3, h4, h5, h6&#8243;]` which isn't working all together.

Is there any other way or can I unescape the shortcode back to it's original state?

**Comment by tcrsavage** [comment]
@dashaluna trac ticket which relates to the issue we can see with applying the_content filter within the shortcode callback.

https://core.trac.wordpress.org/ticket/17817
